language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script: ./gradlew check pitest
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/